(lang dune 3.16)

(name sdkserver)

(generate_opam_files true)

(authors "yuvlian")

(maintainers "yuvlian")

(package
 (name sdkserver)
 (synopsis "ocaml sdkserver")
 (depends ocaml dune tiny_httpd base64 pbrt))
